mesh_files:
  base:
    visual:
      mesh:
        package: ur5e_description
        path: meshes/visual/robotiq_85_base_link.dae
    collision:
      mesh:
        package: ur5e_description
        path: meshes/collision/robotiq_85_base_link.stl


  knuckle:
    visual:
      mesh:
        package: ur5e_description
        path: meshes/visual/robotiq_85_knuckle_link.dae
    collision:
      mesh:
        package: ur5e_description
        path: meshes/collision/robotiq_85_knuckle_link.stl


  finger:
    visual:
      mesh:
        package: ur5e_description
        path: meshes/visual/robotiq_85_finger_link.dae
    collision:
      mesh:
        package: ur5e_description
        path: meshes/collision/robotiq_85_finger_link.stl

  finger_tip:
    visual:
      mesh:
        package: ur5e_description
        path: meshes/visual/robotiq_85_finger_tip_link.dae
    collision:
      mesh:
        package: ur5e_description
        path: meshes/collision/robotiq_85_finger_tip_link.stl

  inner_knuckle:
    visual:
      mesh:
        package: ur5e_description
        path: meshes/visual/robotiq_85_inner_knuckle_link.dae
    collision:
      mesh:
        package: ur5e_description
        path: meshes/collision/robotiq_85_inner_knuckle_link.stl